### ISSUE TITLE
registry simplified ignore user params

### ISSUE THREAD

**Issue by JiaLiangoooo** [apache/dubbo-go#1044]
**What happened**:
consul 只允许512个字符，provider必须要添加参数simplified：true，但是加入simplified会忽略自定义的参数

**What you expected to happen**:
simplified支持自定义参数

**How to reproduce it (as minimally and precisely as possible)**:
在config.load前，将service添加自定义的参数

**Anything else we need to know?**:

**Comment by cityiron** [comment]
You can submit PR for this.

**Comment by AlexStocks** [comment]
@gaoxinge

**Comment by gaoxinge** [comment]
https://github.com/apache/dubbo-go/blob/3a9956a2a24c6736caae198b466a77ee979a5fd4/registry/protocol/protocol.go#L96-L102

In go version code, provider url will only reserve `reserveParams` if there is `simplified` keyword in registry url. This is the same as java version ([[1](https://github.com/apache/dubbo/blob/936c6624d3ce99cd05ebe03ede62dc671cf7b702/dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java#L405)], [[2](https://github.com/apache/dubbo/blob/936c6624d3ce99cd05ebe03ede62dc671cf7b702/dubbo-common/src/main/java/org/apache/dubbo/common/URL.java#L395-L402)]).

In my opinion:

- removing params, which is not reserved keyword, is by design
- the problem is that consul can not work without setting `simplified` keyword, because dubbo-go (or dubbo) register with too many parameters in registry

**Comment by AlexStocks** [comment]
we do not wanna support consul any more.
