### ISSUE TITLE
Ehancement: upgrade gRPC version from 1.26 to 1.36

### ISSUE THREAD

**Issue by AlexStocks** [apache/dubbo-go#1152]
**What would you like to be added**:

upgrade gRPC version.

**Why is this needed**:

using latest gRPC.

**Comment by AlexStocks** [comment]
cc @gaoxinge

**Comment by gaoxinge** [comment]
I think the difficult thing is that we should upgrade the version of `etcd`. This is because `etcd` does not use `go module` before `v3.5.0` ([[1](https://github.com/etcd-io/etcd/issues/11154)], [[2](https://colobu.com/2020/04/09/accidents-of-etcd-and-go-module/)]).

Now the latest version of `github.com/coreos/etcd` is `v3.3.25+incompatible` ([[3](https://pkg.go.dev/go.etcd.io/etcd)]), and highest compatible version of grpc is `v1.26.0`. So we can not directly upgrade grpc to higher version.

In addition, `github.com/coreos/etcd@v3.5.0` will release in the mid of 2021 ([[4](https://github.com/etcd-io/etcd/milestone/37)]), and it may introduce incompatible and conflict codes with `dubbogo`.

**Comment by AlexStocks** [comment]
> I think the difficult thing is that we should upgrade the version of `etcd`. This is because `etcd` does not use `go module` before `v3.5.0` ([[1](https://github.com/etcd-io/etcd/issues/11154)], [[2](https://colobu.com/2020/04/09/accidents-of-etcd-and-go-module/)]).
> 
> Now the latest version of `github.com/coreos/etcd` is `v3.3.25+incompatible` ([[3](https://pkg.go.dev/go.etcd.io/etcd)]), and highest compatible version of grpc is `v1.26.0`. So we can not directly upgrade grpc to higher version.
> 
> In addition, `github.com/coreos/etcd@v3.5.0` will release in the mid of 2021 ([[4](https://github.com/etcd-io/etcd/milestone/37)]), and it may introduce incompatible and conflict codes with `dubbogo`.

ok. I got what u said. let's keep this issue until the autumn of 2021. 

we just upgrade gRPC to 1.26 now.

**Comment by gaoxinge** [comment]
I have updated grpc from 1.26.0 to 1.29.1.  I will try to update it to 1.36 later.

**Comment by gaoxinge** [comment]
https://github.com/apache/dubbo-go/pull/1203 have updated etcd and grpc to latest version and it still needs 

https://github.com/apache/dubbo-go/blob/65774dc90a6162c92acf89ae7a55972c604b9498/go.mod#L70

because of the consul depends the grpc v1.15.1.

But I think we can slow down the pace to update the verion of grpc, and focus on other issues. @AlexStocks @ztelur
