### ISSUE TITLE
The CI is not working

### ISSUE THREAD

**Issue by justxuewei** [apache/dubbo-go#2291]
See https://github.com/apache/dubbo-go/actions/runs/4604922319. The issue is probably caused by the `rpc/jsonrpc` according to the logs. However, it is weird that the CI of dubbo-go-sample doesn't have this issue.

**Comment by chickenlj** [comment]
Here I have located the cause of the problem. In short, the following case will hang for a very long time for some unknow reasons and finally be terminated by SIGINT signal.

![image](https://user-images.githubusercontent.com/18097545/230570381-1e99bb36-e541-40a1-b32e-14704c80a1da.png)

![image](https://user-images.githubusercontent.com/18097545/230570412-424e130a-1d06-48f3-b7d0-3b5b7558f29e.png)

I am investigating the code and trying to find out the root cause right now.
