### ISSUE TITLE
[3.2] The configuration default value flow problem

### ISSUE THREAD

**Issue by FoghostCn** [apache/dubbo-go#2592]
### Issue description

The configuration default value flow problem, instanceOptions -> ServerOptions/ClientOptions -> ServiceOptions is the default value flow direction, and should not flow in the reverse direction. Each level inherits the default value of the previous level and can be modified at the current level. It should not affect the previous level. level value, the current implementation will synchronize back to InstanceOptions when modifying some configurations at the server layer.

配置的默认值流向问题，instanceOptions -> ServerOptions/ClientOptions -> ServiceOptions 为默认值流向，而不应该反向流动，每一级继承上一级的默认值，可以在当前层级修改，不应该影响上一级的值，目前的实现 在 server 层修改一些配置会同步回 InstanceOptions

**Comment by setcy** [comment]
I'm interested in this issue, can it be assigned to me?

Here is my proposal:

## Background
```go
// NewClient is like client.NewClient, but inject configurations from RootConfig and
// ConsumerConfig
func (ins *Instance) NewClient(opts ...client.ClientOption) (*client.Client, error) {
	if ins == nil || ins.insOpts == nil {
		return nil, errors.New("Instance has not been initialized")
	}

	var cliOpts []client.ClientOption
	conCfg := ins.insOpts.Consumer
	appCfg := ins.insOpts.Application
	regsCfg := ins.insOpts.Registries
	sdCfg := ins.insOpts.Shutdown
	metricsCfg := ins.insOpts.Metrics
	otelCfg := ins.insOpts.Otel
        ...
}
```

## Proposal
In the current implementation of the `NewClient`, `NewServer` method, since configurations are passed directly to methods via pointers. Since the pointer refers to the same object, any modifications to the configuration options are reflected back on the original Instance object.

To address the aforementioned issues, I consider to use deep copied configurations to create clients, and implement respective deep copy functions in each type of configuration item. The design code will look like this:
```go
	conCfg := ins.ConsumerOpts()
	appCfg := ins.ApplicationOpts()
	regsCfg := ins.RegistriesOpts()
	sdCfg := ins.ShutdownOpts()
	metricsCfg := ins.MetricsOpts()
	otelCfg := ins.OtelOpts()
```
