### ISSUE TITLE
Align 2.7.5: EurekaServiceDiscovery

### ISSUE THREAD

**Issue by flycash** [apache/dubbo-go#424]
**What would you like to be added**:
EurekaServiceDiscovery, the implementation of ServiceDiscovery based on eureka

**Why is this needed**:

**Comment by zouyx** [comment]
I will close this issue , because there is a low ROI feature .
Reason as below.
1. 3rd party pakcage can not support the fully feature with eureka then need to redevelop for it . 
2. Spring cloud had stoped maintenance in last few years.
3. I don't know how many users use this feature in dubbo , also dubbo-go.
