### ISSUE TITLE
zookeeper注册中心有bug吗

### ISSUE THREAD

**Issue by jack15083** [apache/dubbo-go#727]
**What happened**:
当我在服务端泛化调用另一个服务端的rpc服务时，在consumer.yml 增加如下配置 发现如果增加generic = true 会导致provider 的服务注册不成功，启用应用的时候也没有任何报错，照理说改consumer端的配置应该不会影响服务端的吧

![image](https://user-images.githubusercontent.com/2142066/91028251-ca4b3800-e62f-11ea-9f75-a2f02e2bc7d7.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by zouyx** [comment]
你是用了同一个配置文件吗？如果是两个服务分别使用两个配置文件应该不会有问题。

**Comment by jack15083** [comment]
没有只是一个服务使用一个配置文件  就是启动一个provider服务里分别有provider.yml跟consumer.yml然后  consumer.yml 如果增加generic = true 就会导致proivder.yml里注的服务注册不成功，你可以测试一下看看

**Comment by zouyx** [comment]
> 没有只是一个服务使用一个配置文件 就是启动一个provider服务里分别有provider.yml跟consumer.yml然后 consumer.yml 如果增加generic = true 就会导致proivder.yml里注的服务注册不成功，你可以测试一下看看

我知道了，你是都在一个进程里面启动 provider 和 consumer 是吧？如果是的话，现在 @DogBaoBao 正在测试这么做行不行。

**Comment by IronCity** [comment]
> 没有只是一个服务使用一个配置文件 就是启动一个provider服务里分别有provider.yml跟consumer.yml然后 consumer.yml 如果增加generic = true 就会导致proivder.yml里注的服务注册不成功，你可以测试一下看看

Thanks you,  this is a good case, I will run this sample this week.

**Comment by DogBaoBao** [comment]
> 没有只是一个服务使用一个配置文件 就是启动一个provider服务里分别有provider.yml跟consumer.yml然后 consumer.yml 如果增加generic = true 就会导致proivder.yml里注的服务注册不成功，你可以测试一下看看

Thanks you, this is a good case, I will run this sample this week.

**Comment by jack15083** [comment]
是的同时启动了 provider 和 consumer  因为服务端也可能作为consumer端去泛化调用别的服务

**Comment by DogBaoBao** [comment]
I run the sample, but not found this.

my client.yml
![image](https://user-images.githubusercontent.com/55343460/92345282-60389580-f0fb-11ea-924e-defc9bc01663.png)

I run a service(product), and run a service(order with generic:true in client.yml), I can found provider in zk:

![image](https://user-images.githubusercontent.com/55343460/92345459-f10f7100-f0fb-11ea-801c-e23a1f57b857.png)

I only see can't invoke 
```go
err := productProvider.GetProduct(context.TODO(), []interface{}{"A001"}, product)
```
because when config generic = true exist,  generic_service_filter will run.

**Comment by zouyx** [comment]
@jack15083 any other questions?

**Comment by jack15083** [comment]
又测试了几遍没有还原之前的问题，很奇怪有可能是我之前测试的时候，有些配置有问题吧，感谢花时间测试这个issue。
